### PR TITLE
Turn usage into a grid, because grids are cool

### PR DESCRIPTION
**Pull request by Steve0Greatness**
Reason: grids are cool.
Problem with the old way: it's not a grid, and grids are cool.

But really, this automatically adds spaces, meaning if new longer commands are added then all other lines don't need to be re-formatted manually(this would get especially tedious the more commands added).

### CODE REVIEW

**Comment by MystPi** [comment]
~~Could you give an example of what this would output?~~ Never mind, I think I've got it.

**Comment by MystPi** [comment]
I have a few problems with this:
- Kind of minor, but there is an added runtime cost when it has to calculate padding each time the help message is shown
- I think you may have overcomplicated things. Remember that Gleam is a functional programming language: there shouldn't be any mutability going on.
- Since you are only using `gleam_javascript` for mutability, it isn't needed.

Overall, I think this is a good idea, but the implementation would have to change before it is merged.

**Comment by MystPi** [comment]
Here is an alternative:
```gleam
const usage = [
  #("create <name>", "Create a new project"),
  #("run", "Run the current project"),
  #("<path>", "Run the given file"),
]

pub fn main() {
  case utils.get_args(), get_project() {
    _, #(True, Error(msg)) -> error(msg)
    ["create", name, ..], _ -> create_project(name)
    ["run", ..], #(True, Ok(project)) -> run_project(project.name)
    [path, ..], _ -> run_file(path)
    _, _ -> print_usage()
  }
}

fn print_usage() -> Nil {
  let assert Ok(max_len) =
    usage
    |> list.map(fn(x) { string.length(x.0) })
    |> list.sort(int.compare)
    |> list.last

  io.println("Usage:")

  usage
  |> list.each(fn(x) {
    let #(command, desc) = x
    let left_over = max_len - string.length(command) + 2
    io.println("  bella " <> command <> string.repeat(" ", left_over) <> desc)
  })
}
```
Output:
```
Usage:
  bella create <name>  Create a new project
  bella run            Run the current project
  bella <path>         Run the given file
```
Do you mind if I use this instead?

**Comment by Steve0Greatness** [comment]
Sure.

**Pull request closed without merging**
